version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: saiya-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: saiya_gym
      MYSQL_USER: saiya_user
      MYSQL_PASSWORD: saiya_pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [CMD-SHELL, mysqladmin ping -h 127.0.0.1 -u root -p7118MYSQL_ROOT_PASSWORD]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  mysql_data:

