version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/saiya_gym
      SPRING_DATASOURCE_USERNAME: saiya_user
      SPRING_DATASOURCE_PASSWORD: saiya_pass
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: saiya_gym
      MYSQL_USER: saiya_user
      MYSQL_PASSWORD: saiya_pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, mysqladmin ping -h 127.0.0.1 -u root -p39517MYSQL_ROOT_PASSWORD]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:

